### PR TITLE
Use the latest datasources.txt.

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by ariutta** [comment]
The URL https://cdn.rawgit.com/bridgedb/BridgeDb/master/org.bridgedb.bio/resources/org/bridgedb/bio/datasources.txt is intended for development only. Rawgit.com says that for development URLs:

>Excessive traffic will be throttled and blacklisted.

>If excessive traffic continues, RawGit will display a prominent error message on your website to try to get your attention.

@AlexanderPico, is this URL requested each time a user visits, or does WikiPathways.org request it just once and then cache it on the WikiPathways.org server? If it's just requested once, the development URL wouldn't be overwhelmed with requests. But we would need to make sure to have  WikiPathways.org get and cache the new version when we update datasources.txt in the BridgeDb repo.

[This describes](https://github.com/bridgedb/bridgedbjs#dependencies) how we do it for bridgedbjs.

**Comment by AlexanderPico** [comment]
My guess is that even full, uncached production use of WikiPathways would not qualify as "excessive traffic" by rawgit standards :)   I'd just continue to use it until notified otherwise.

**Comment by egonw** [comment]
@AlexanderPico @ariutta, so, what is next? How do I mark this as hotfix for the main wikipathways.org website and get something to deploy this fix?

**Comment by AlexanderPico** [comment]
For something this contained (i.e., a couple lines in a single file), I would not recommend making (or waiting for) a new release. Just make the same changes in the live code... the hottest fix possible! :)

**Pull request merged**
