### PR TITLE
Adds a link out to Europe PMC.

### PR DESCRIPTION
**Pull request by egonw**
Hi all, since Europe PMC is linking to us, why not link to them in our Bibliography too?

### CODE REVIEW

**Comment by Chris-Evelo** [comment]
Nice, but can be confusing. We clearly need to discriminate between literature references that say "this pathway based on" versus references that say "this pathway featured in". But in principle, we could show both.

**Comment by egonw** [comment]
@Chris-Evelo, if you think the current bibliography is confusing, please file a bug report for that. This patch is not about change the current behavior of how the bibliography is shown on WikiPathways (or what is shown as part of that).

**Comment by Chris-Evelo** [comment]
No, I do not think the current behavior is confusing, not for how we used it so far. So far, as far as I know, we only captured references of the form "this pathway based upon". If you indeed now propose to add references of the type "this pathway used in" then we might want to discriminate these in the GPML and show them separately on the Wiki.

**Comment by egonw** [comment]
The patch is not adding references.

**Comment by Chris-Evelo** [comment]
Sorry, misunderstood

**Comment by AlexanderPico** [comment]
It works and is now live.

**Comment by AlexanderPico** [comment]
More importantly, I added it to the new codebase: https://github.com/wikipathways/mediawiki-extensions-WikiPathways/blob/master/src/PathwayBibliography.php#L75

Please file feature requests on the new repos.

**Comment by egonw** [comment]
Thx. Will do.

**Pull request merged**
